image:
  source: ${artifact.metadata.image}
  pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "300m"
      memory: "150Mi"
    requests:
      cpu: "200m"
      memory: "100Mi"
args:
  tillerNamespace: secure-helm
ingress:
  fqdn:
  class: internal
  certSecretName:
  affinity: ''
<<<<<<< HEAD
=======

ingress:
  fqdn: ${workflow.variables.fqdn-dev-esp-awslab}
>>>>>>> Update values.yaml
