image:
  source: ${artifact.metadata.image}
  pullPolicy: Always
  resources:
    limits:
      cpu: "300m"
      memory: "150Mi"
    requests:
      cpu: "200m"
      memory: "100Mi"
args:
  tillerNamespace: secure-helm
ingress:
  class: internal
  fqdn: ${workflow.variables.fqdn_dev_esp_awslab}
  certSecretName:
  affinity: ''
